---
title: "Data_prep"
author: "Kamau Lindhardt, lbk125"
date: "5/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages to be installed
```{r}
install.packages('tidygeocoder')
```

Loading libraries
```{r}
library(tidygeocoder)

library(tidyverse)
library(readxl)
library(ggplot2)
```

Loading data
```{r}
data <- read_excel("DATA/SILVOARABLE_REVIEW_DATA_FOR_ANALYSIS.xlsx")
#View(data) 
```

Adding latitude and longitude of study locations
```{r}
data_lat_longs <- data %>%
  geocode(`Location Specification`, method = 'osm', lat = latitude , long = longitude)

View(data_lat_longs)
```

Listing studies with missing value in the Latitude column
```{r}
loacation_missing <- data_lat_longs %>%
  filter_all(any_vars(is.na(latitude))) %>%
  relocate(latitude, longitude, `Location Specification`, StLocation, n, Title)

View(loacation_missing)

# The 28 studies with missing information for the latitude location were then manually checked and edited where possible by re-visiting the papers. The previous lines of code was run again. 
```

Replacing the observations that have missing values in 'Location Specification' with the information from the general 'Location' column
```{r}
data_lat_longs_no_missing %>%

```

Visualising the locations on a map
```{r}
ggplot(data_lat_longs, aes(longitude, latitude), color = "grey99") +
  borders("world") + geom_point(color = "orange") +
  #ggrepel::geom_label_repel(aes(label = n)) +
  theme_void()
```

