---
title: "Literature_review_Sankey_diagram"
author: "Kamau Lindhardt, lbk125"
date: "6/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages

```{r}
library(readxl)
library(tidyverse)
#devtools::install_github("davidsjoberg/ggsankey")
library(ggsankey)
#install.packages("networkD3")
library(networkD3)
library(dplyr)
library(ggplot2)
```


# Sankey diagram

```{r}
# Create an incidence matrix. Usually the flow goes from the row names to the column names.
# Remember that our connection are directed since we are working with a flow.

# A connection data frame is a list of flows with intensity for each flow
links <- data.frame(
  source=c("Other literature sources",              # 1
           "Literature from database search",       # 2
           "",                                      # 3
           "",                                      # 4
           "",                                      # 5
           "",                                      # 6
           "",                                      # 7
           ""),                                     # 8
  
  target=c("",                                       
           "", 
           "Excleded (Duplications)",               # 1
           "Excluded (Limiting per document type)", # 2
           "Excluded (Title + Abstract screening)", # 3
           "Excluded (Reviews)",                    # 4
           "Excluded (Full text screening)",        # 5
           "Included for analysis"),                # 6
  
  value=c(4,      # Other sources                         - 0.2 %
          2101,   # Literature sources from databases     - 99.8 %
          172,    # Excluded - Duplication                - 8.2 %  
          90,     # Excluded - Limiting per document type - 4.3 % 
          1578,   # Excluded - Title + Abstract screening - 75 %
          79,     # Excluded - Reviews                    - 3.8 %
          102,    # Excluded - Full text screening        - 4.8 %
          83)     # Included for analysis                 - 3.9 %
  )
 
# From these flows we need to create a node data frame: it lists every entities involved in the flow
nodes <- data.frame(
  name=c(as.character(links$source), 
  as.character(links$target)) %>% unique()
)
 
# With networkD3, connection must be provided using id, not using real name like in the links dataframe.. So we need to reformat it.
links$IDsource <- match(links$source, nodes$name)-1 
links$IDtarget <- match(links$target, nodes$name)-1
 
# Make the Network
p <- sankeyNetwork(Links = links, Nodes = nodes,
              Source = "IDsource", Target = "IDtarget",
              Value = "value", NodeID = "name", 
              fontSize= 12, nodeWidth = 1,
              sinksRight=FALSE)
p
```

```{r}
# you save it as an html
saveNetwork(p, "p.html")

library(webshot)
# you convert it as png
webshot("p.html","p.png", vwidth = 1000, vheight = 900)
```



```{r}
# # Create an incidence matrix. Usually the flow goes from the row names to the column names.
# # Remember that our connection are directed since we are working with a flow.
# 
# # A connection data frame is a list of flows with intensity for each flow
# links <- data.frame(
#   source=c("group_A","group_B", "group_C", "group_C", "group_C", "group_C"), 
#   target=c("group_C","group_C", "group_D", "group_E", "group_F", "group_G"), 
#   value=c(35, 595, 95, 159, 123, 99)
#   )
#  
# # From these flows we need to create a node data frame: it lists every entities involved in the flow
# nodes <- data.frame(
#   name=c(as.character(links$source), 
#   as.character(links$target)) %>% unique()
# )
#  
# # With networkD3, connection must be provided using id, not using real name like in the links dataframe.. So we need to reformat it.
# links$IDsource <- match(links$source, nodes$name)-1 
# links$IDtarget <- match(links$target, nodes$name)-1
#  
# # Make the Network
# p <- sankeyNetwork(Links = links, Nodes = nodes,
#               Source = "IDsource", Target = "IDtarget",
#               Value = "value", NodeID = "name", 
#               fontSize= 12, nodeWidth = 1,
#               sinksRight=FALSE)
# p
```







